const properties=[
 {id:1,title:'3-Bedroom Apartment in Uttara',price:6600000,type:'Apartment',city:'Dhaka',location:'Uttara, Dhaka',meta:'3 Beds • 2 Baths • 1,450 Sq Ft',img:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80',verified:true},
 {id:2,title:'4 Katha Residential Plot',price:10300000,type:'Land',city:'Dhaka',location:'Bashundhara R/A, Dhaka',meta:'4 Katha • North Facing • 25 ft Road',img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80',verified:true},
 {id:3,title:'Modern 3 Bedroom Flat for Sale',price:8500000,type:'Apartment',city:'Chattogram',location:'Khulshi, Chattogram',meta:'3 Beds • 3 Baths • 1,600 Sq Ft',img:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=80',verified:false},
 {id:4,title:'Furnished 2 Bedroom Apartment',price:25000,type:'Apartment',city:'Dhaka',location:'Shyamoli, Dhaka',meta:'2 Beds • 2 Baths • Furnished',img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',verified:true,rent:true},
 {id:5,title:'5 Katha Plot Near Main Road',price:11000000,type:'Land',city:'Dhaka',location:'Bashundhara, Dhaka',meta:'5 Katha • North Facing • 200 ft Road',img:'https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=900&q=80',verified:true},
 {id:6,title:'Commercial Office Space',price:4500000,type:'Commercial',city:'Dhaka',location:'Motijheel, Dhaka',meta:'2,100 Sq Ft • Main Road • Lift',img:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80',verified:false},
 {id:7,title:'Family House for Rent',price:490000,type:'House',city:'Dhaka',location:'Bashundhara R/A, Dhaka',meta:'5 Beds • 4 Baths • Furnished',img:'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=900&q=80',verified:true,rent:true},
 {id:8,title:'Residential Land — Ready for Sale',price:3500000,type:'Land',city:'Nilphamari',location:'Nilphamari Sadar, Nilphamari',meta:'10 Decimal • Road Access • Clear Docs',img:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=900&q=80',verified:false}
];
let current=properties.slice();
function money(n){return '৳ '+n.toLocaleString('en-BD')}
function render(list=current){const grid=document.getElementById('listingGrid');grid.innerHTML=list.map(p=>`<article class="card"><div class="photo" style="background-image:url('${p.img}')"><span class="badge">${p.rent?'FOR RENT':'FOR SALE'}</span><button class="heart" onclick="event.stopPropagation();this.textContent=this.textContent==='♡'?'♥':'♡'">♡</button></div><div class="card-body"><div class="price">${money(p.price)} ${p.rent?'<small>/ month</small>':''}</div><div class="title">${p.title}</div><div class="meta">${p.meta}</div><div class="location-text">📍 ${p.location}</div><div class="seller">${p.verified?'<span class="verified">✓ Verified</span>':'<span>Owner / Agent</span>'}<span>• Updated recently</span></div></div></article>`).join('');document.getElementById('resultCount').textContent=`${list.length} results`}
function filterProperties(){const city=document.getElementById('location').value;const type=document.getElementById('type').value;const min=Number(document.getElementById('minPrice').value)||0;const max=Number(document.getElementById('maxPrice').value)||Infinity;const checked=[...document.querySelectorAll('.type-check:checked')].map(x=>x.value);current=properties.filter(p=>(!city||p.city===city)&&(!type||p.type===type)&&(!checked.length||checked.includes(p.type))&&p.price>=min&&p.price<=max);sortProperties();}
function sortProperties(){const s=document.getElementById('sort').value;current.sort((a,b)=>s==='low'?a.price-b.price:s==='high'?b.price-a.price:b.id-a.id);render()}
function resetFilters(){document.getElementById('location').value='';document.getElementById('type').value='';document.getElementById('minPrice').value='';document.getElementById('maxPrice').value='';document.querySelectorAll('.type-check').forEach(x=>x.checked=false);current=properties.slice();render()}
function openPostModal(){document.getElementById('postModal').classList.add('open')}
function closePostModal(){document.getElementById('postModal').classList.remove('open')}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');const mode=tab.dataset.mode;if(mode==='rent'){current=properties.filter(p=>p.rent)}else if(mode==='land'){current=properties.filter(p=>p.type==='Land')}else if(mode==='commercial'){current=properties.filter(p=>p.type==='Commercial')}else{current=properties.filter(p=>!p.rent)}render(current)}));
render();
